package com.jessicagray.geotrack;

import com.jessicagray.geotrack.model.Organisation;
import com.jessicagray.geotrack.model.Project;
import com.jessicagray.geotrack.model.User;
import com.jessicagray.geotrack.repository.ProjectRepository;
import com.jessicagray.geotrack.repository.UserRepository;
import com.jessicagray.geotrack.service.ProjectService;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class ProjectServiceTests {

    private ProjectRepository projectRepository;
    private UserRepository userRepository;
    private ProjectService projectService;

    private Organisation organisation;
    private User user;

    @BeforeEach
    void setUp() {

        projectRepository =
                mock(ProjectRepository.class);

        userRepository =
                mock(UserRepository.class);

        projectService =
                new ProjectService(
                        projectRepository,
                        userRepository
                );

        /*
         * Create a test organisation.
         *
         * Organisation's ID is generated by JPA in the real
         * application. For these unit tests we mock the
         * organisation so we can provide a predictable ID.
         */
        organisation =
                mock(Organisation.class);

        when(organisation.getId())
                .thenReturn(1L);

        when(organisation.isEnabled())
                .thenReturn(true);

        /*
         * Create the authenticated GeoTrack test user.
         */
        user = new User(
                "testuser",
                "password",
                "STAFF"
        );

        user.setOrganisation(organisation);

        when(
                userRepository.findByEmailIgnoreCase(
                        "testuser"
                )
        ).thenReturn(Optional.empty());

        when(
                userRepository.findByUsernameIgnoreCase(
                        "testuser"
                )
        ).thenReturn(Optional.of(user));

        /*
         * Pretend that "testuser" is currently logged in
         * through Spring Security.
         */
        UsernamePasswordAuthenticationToken authentication =
                new UsernamePasswordAuthenticationToken(
                        "testuser",
                        "password",
                        List.of()
                );

        SecurityContextHolder
                .getContext()
                .setAuthentication(authentication);
    }

    @AfterEach
    void tearDown() {

        SecurityContextHolder.clearContext();
    }

    @Test
    void shouldGetAllProjectsForCurrentOrganisation() {

        Project project = new Project();

        when(
                projectRepository
                        .findAllByOrganisationId(1L)
        ).thenReturn(List.of(project));

        List<Project> result =
                projectService.getAllProjects();

        assertEquals(1, result.size());

        verify(projectRepository)
                .findAllByOrganisationId(1L);

        verify(projectRepository, never())
                .findAll();
    }

    @Test
    void shouldGetProjectByIdForCurrentOrganisation() {

        Project project = new Project();

        when(
                projectRepository
                        .findByIdAndOrganisationId(
                                1L,
                                1L
                        )
        ).thenReturn(Optional.of(project));

        Optional<Project> result =
                projectService.getProjectById(1L);

        assertTrue(result.isPresent());

        verify(projectRepository)
                .findByIdAndOrganisationId(
                        1L,
                        1L
                );
    }

    @Test
    void shouldReturnEmptyWhenProjectDoesNotExistInOrganisation() {

        when(
                projectRepository
                        .findByIdAndOrganisationId(
                                99L,
                                1L
                        )
        ).thenReturn(Optional.empty());

        Optional<Project> result =
                projectService.getProjectById(99L);

        assertTrue(result.isEmpty());

        verify(projectRepository)
                .findByIdAndOrganisationId(
                        99L,
                        1L
                );
    }

    @Test
    void shouldCreateProjectForCurrentOrganisation() {

        Project project = new Project();

        when(projectRepository.save(project))
                .thenReturn(project);

        Project result =
                projectService.createProject(project);

        assertNotNull(result);

        assertSame(project, result);

        assertSame(
                organisation,
                project.getOrganisation()
        );

        verify(projectRepository)
                .save(project);
    }

    @Test
    void shouldDeleteProjectFromCurrentOrganisation() {

        Project project = new Project();

        when(
                projectRepository
                        .findByIdAndOrganisationId(
                                1L,
                                1L
                        )
        ).thenReturn(Optional.of(project));

        projectService.deleteProject(1L);

        verify(projectRepository)
                .findByIdAndOrganisationId(
                        1L,
                        1L
                );

        verify(projectRepository)
                .delete(project);

        verify(projectRepository, never())
                .deleteById(1L);
    }

    @Test
    void shouldThrowExceptionWhenUpdatingMissingProject() {

        Project updatedProject =
                new Project();

        when(
                projectRepository
                        .findByIdAndOrganisationId(
                                99L,
                                1L
                        )
        ).thenReturn(Optional.empty());

        assertThrows(
                RuntimeException.class,
                () -> projectService.updateProject(
                        99L,
                        updatedProject
                )
        );

        verify(projectRepository)
                .findByIdAndOrganisationId(
                        99L,
                        1L
                );
    }

    @Test
    void shouldNotAccessProjectFromAnotherOrganisation() {

        /*
         * Project 50 may exist in the database, but if it
         * does not belong to organisation 1 the repository
         * must return nothing.
         */
        when(
                projectRepository
                        .findByIdAndOrganisationId(
                                50L,
                                1L
                        )
        ).thenReturn(Optional.empty());

        Optional<Project> result =
                projectService.getProjectById(50L);

        assertTrue(result.isEmpty());

        verify(projectRepository)
                .findByIdAndOrganisationId(
                        50L,
                        1L
                );

        /*
         * Critically, GeoTrack must not fall back to a
         * global findById() lookup.
         */
        verify(projectRepository, never())
                .findById(50L);
    }
}