package com.jessicagray.geotrack;

import com.jessicagray.geotrack.model.Organisation;
import com.jessicagray.geotrack.model.Project;
import com.jessicagray.geotrack.model.SiteInvestigation;
import com.jessicagray.geotrack.model.User;
import com.jessicagray.geotrack.repository.ProjectRepository;
import com.jessicagray.geotrack.repository.SiteInvestigationRepository;
import com.jessicagray.geotrack.repository.UserRepository;
import com.jessicagray.geotrack.service.SiteInvestigationService;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;

import java.util.List;
import java.util.Optional;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class SiteInvestigationTests {

    private static ValidatorFactory validatorFactory;
    private static Validator validator;

    @Mock
    private SiteInvestigationRepository investigationRepository;

    @Mock
    private ProjectRepository projectRepository;

    @Mock
    private UserRepository userRepository;

    private SiteInvestigationService service;

    private Organisation currentOrganisation;
    private User currentUser;

    @BeforeAll
    static void setUpValidator() {

        validatorFactory =
                Validation.buildDefaultValidatorFactory();

        validator =
                validatorFactory.getValidator();
    }

    @AfterAll
    static void tearDownValidator() {

        validatorFactory.close();
    }

    @BeforeEach
    void setUpService() {

        service = new SiteInvestigationService(
                investigationRepository,
                projectRepository,
                userRepository
        );

        /*
         * Organisation IDs are generated by JPA in the
         * real application. The Organisation entity has
         * no public setId() method, so Mockito supplies
         * the test organisation ID.
         */
        currentOrganisation =
                mock(Organisation.class);

        /*
         * These stubbings are lenient because the class
         * contains both validation-only tests and service
         * tenancy tests. Validation tests do not use the
         * authenticated organisation.
         */
        lenient()
                .when(currentOrganisation.getId())
                .thenReturn(1L);

        lenient()
                .when(currentOrganisation.isEnabled())
                .thenReturn(true);

        currentUser = new User();
        currentUser.setUsername("testuser");
        currentUser.setEmail("testuser@example.com");
        currentUser.setOrganisation(
                currentOrganisation
        );
        currentUser.setEnabled(true);

        UsernamePasswordAuthenticationToken authentication =
                new UsernamePasswordAuthenticationToken(
                        "testuser",
                        "password",
                        List.of()
                );

        SecurityContextHolder
                .getContext()
                .setAuthentication(authentication);

        lenient()
                .when(
                        userRepository.findByEmailIgnoreCase(
                                "testuser"
                        )
                )
                .thenReturn(Optional.empty());

        lenient()
                .when(
                        userRepository.findByUsernameIgnoreCase(
                                "testuser"
                        )
                )
                .thenReturn(Optional.of(currentUser));
    }

    @AfterEach
    void clearSecurityContext() {

        SecurityContextHolder.clearContext();
    }

    /*
     * ---------------------------------------------------------
     * VALIDATION TESTS
     * ---------------------------------------------------------
     */

    @Test
    void shouldAcceptValidInvestigation() {

        SiteInvestigation investigation =
                new SiteInvestigation(
                        "INV-001",
                        "Ground Investigation",
                        "Harlow",
                        "PLANNED",
                        "2026-09-10",
                        "Initial site investigation"
                );

        Set<ConstraintViolation<SiteInvestigation>>
                violations =
                validator.validate(investigation);

        assertTrue(violations.isEmpty());
    }

    @Test
    void shouldRejectBlankInvestigationReference() {

        SiteInvestigation investigation =
                new SiteInvestigation(
                        "",
                        "Ground Investigation",
                        "Harlow",
                        "PLANNED",
                        "2026-09-10",
                        "Notes"
                );

        Set<ConstraintViolation<SiteInvestigation>>
                violations =
                validator.validate(investigation);

        assertTrue(
                violations.stream()
                        .anyMatch(violation ->
                                violation
                                        .getPropertyPath()
                                        .toString()
                                        .equals(
                                                "investigationReference"
                                        )
                        )
        );
    }

    @Test
    void shouldRejectBlankInvestigationType() {

        SiteInvestigation investigation =
                new SiteInvestigation(
                        "INV-001",
                        "",
                        "Harlow",
                        "PLANNED",
                        "2026-09-10",
                        "Notes"
                );

        Set<ConstraintViolation<SiteInvestigation>>
                violations =
                validator.validate(investigation);

        assertTrue(
                violations.stream()
                        .anyMatch(violation ->
                                violation
                                        .getPropertyPath()
                                        .toString()
                                        .equals(
                                                "investigationType"
                                        )
                        )
        );
    }

    @Test
    void shouldRejectBlankLocation() {

        SiteInvestigation investigation =
                new SiteInvestigation(
                        "INV-001",
                        "Ground Investigation",
                        "",
                        "PLANNED",
                        "2026-09-10",
                        "Notes"
                );

        Set<ConstraintViolation<SiteInvestigation>>
                violations =
                validator.validate(investigation);

        assertTrue(
                violations.stream()
                        .anyMatch(violation ->
                                violation
                                        .getPropertyPath()
                                        .toString()
                                        .equals(
                                                "location"
                                        )
                        )
        );
    }

    @Test
    void shouldRejectBlankStatus() {

        SiteInvestigation investigation =
                new SiteInvestigation(
                        "INV-001",
                        "Ground Investigation",
                        "Harlow",
                        "",
                        "2026-09-10",
                        "Notes"
                );

        Set<ConstraintViolation<SiteInvestigation>>
                violations =
                validator.validate(investigation);

        assertTrue(
                violations.stream()
                        .anyMatch(violation ->
                                violation
                                        .getPropertyPath()
                                        .toString()
                                        .equals(
                                                "status"
                                        )
                        )
        );
    }

    @Test
    void shouldRejectBlankDate() {

        SiteInvestigation investigation =
                new SiteInvestigation(
                        "INV-001",
                        "Ground Investigation",
                        "Harlow",
                        "PLANNED",
                        "",
                        "Notes"
                );

        Set<ConstraintViolation<SiteInvestigation>>
                violations =
                validator.validate(investigation);

        assertTrue(
                violations.stream()
                        .anyMatch(violation ->
                                violation
                                        .getPropertyPath()
                                        .toString()
                                        .equals(
                                                "date"
                                        )
                        )
        );
    }

    @Test
    void shouldRejectOversizedNotes() {

        String longNotes =
                "A".repeat(1001);

        SiteInvestigation investigation =
                new SiteInvestigation(
                        "INV-001",
                        "Ground Investigation",
                        "Harlow",
                        "PLANNED",
                        "2026-09-10",
                        longNotes
                );

        Set<ConstraintViolation<SiteInvestigation>>
                violations =
                validator.validate(investigation);

        assertTrue(
                violations.stream()
                        .anyMatch(violation ->
                                violation
                                        .getPropertyPath()
                                        .toString()
                                        .equals(
                                                "notes"
                                        )
                        )
        );
    }

    /*
     * ---------------------------------------------------------
     * TENANT ISOLATION TESTS
     * ---------------------------------------------------------
     */

    @Test
    void shouldReturnOnlyCurrentOrganisationInvestigations() {

        SiteInvestigation investigation =
                new SiteInvestigation(
                        "INV-TENANT-001",
                        "Borehole",
                        "Harlow",
                        "PLANNED",
                        "2026-09-10",
                        "Tenant isolation test"
                );

        investigation.setOrganisation(
                currentOrganisation
        );

        when(
                investigationRepository
                        .findAllByOrganisationId(1L)
        ).thenReturn(
                List.of(investigation)
        );

        List<SiteInvestigation> result =
                service.getAllInvestigations();

        assertEquals(
                1,
                result.size()
        );

        assertEquals(
                "INV-TENANT-001",
                result.get(0)
                        .getInvestigationReference()
        );

        verify(
                investigationRepository
        ).findAllByOrganisationId(1L);

        verify(
                investigationRepository,
                never()
        ).findAll();
    }

    @Test
    void shouldAllowAccessToInvestigationInCurrentOrganisation() {

        SiteInvestigation investigation =
                new SiteInvestigation(
                        "INV-TENANT-002",
                        "Borehole",
                        "Harlow",
                        "PLANNED",
                        "2026-09-10",
                        "Same organisation test"
                );

        investigation.setOrganisation(
                currentOrganisation
        );

        when(
                investigationRepository
                        .findByIdAndOrganisationId(
                                18L,
                                1L
                        )
        ).thenReturn(
                Optional.of(investigation)
        );

        Optional<SiteInvestigation> result =
                service.getInvestigationById(
                        18L
                );

        assertTrue(
                result.isPresent()
        );

        assertEquals(
                "INV-TENANT-002",
                result.get()
                        .getInvestigationReference()
        );

        verify(
                investigationRepository
        ).findByIdAndOrganisationId(
                18L,
                1L
        );
    }

    @Test
    void shouldBlockAccessToInvestigationFromAnotherOrganisation() {

        when(
                investigationRepository
                        .findByIdAndOrganisationId(
                                99L,
                                1L
                        )
        ).thenReturn(
                Optional.empty()
        );

        Optional<SiteInvestigation> result =
                service.getInvestigationById(
                        99L
                );

        assertTrue(
                result.isEmpty()
        );

        verify(
                investigationRepository
        ).findByIdAndOrganisationId(
                99L,
                1L
        );

        verify(
                investigationRepository,
                never()
        ).findById(99L);
    }

    @Test
    void shouldAutomaticallyAssignCurrentOrganisationWhenCreatingInvestigation() {

        SiteInvestigation investigation =
                new SiteInvestigation(
                        "INV-TENANT-003",
                        "Trial Pit",
                        "Cambridge",
                        "PLANNED",
                        "2026-09-10",
                        "Creation tenant test"
                );

        when(
                investigationRepository.save(
                        investigation
                )
        ).thenReturn(
                investigation
        );

        SiteInvestigation result =
                service.createInvestigation(
                        investigation
                );

        assertSame(
                currentOrganisation,
                result.getOrganisation()
        );

        assertNull(
                result.getProject()
        );

        verify(
                investigationRepository
        ).save(investigation);
    }

    @Test
    void shouldBlockUpdateOfInvestigationFromAnotherOrganisation() {

        SiteInvestigation update =
                new SiteInvestigation(
                        "HACKED-INV",
                        "Borehole",
                        "London",
                        "COMPLETED",
                        "2026-09-10",
                        "Cross tenant update attempt"
                );

        when(
                investigationRepository
                        .findByIdAndOrganisationId(
                                99L,
                                1L
                        )
        ).thenReturn(
                Optional.empty()
        );

        RuntimeException exception =
                assertThrows(
                        RuntimeException.class,
                        () ->
                                service.updateInvestigation(
                                        99L,
                                        update
                                )
                );

        assertEquals(
                "Investigation not found",
                exception.getMessage()
        );

        verify(
                investigationRepository,
                never()
        ).save(
                any(SiteInvestigation.class)
        );

        verify(
                investigationRepository,
                never()
        ).findById(99L);
    }

    @Test
    void shouldBlockDeletionOfInvestigationFromAnotherOrganisation() {

        when(
                investigationRepository
                        .findByIdAndOrganisationId(
                                99L,
                                1L
                        )
        ).thenReturn(
                Optional.empty()
        );

        RuntimeException exception =
                assertThrows(
                        RuntimeException.class,
                        () ->
                                service.deleteInvestigation(
                                        99L
                                )
                );

        assertEquals(
                "Investigation not found",
                exception.getMessage()
        );

        verify(
                investigationRepository,
                never()
        ).delete(
                any(SiteInvestigation.class)
        );

        verify(
                investigationRepository,
                never()
        ).findById(99L);
    }

    @Test
    void shouldAllowProjectAssignmentWithinSameOrganisation() {

        SiteInvestigation investigation =
                new SiteInvestigation(
                        "INV-TENANT-004",
                        "Borehole",
                        "Harlow",
                        "PLANNED",
                        "2026-09-10",
                        "Same tenant assignment"
                );

        investigation.setOrganisation(
                currentOrganisation
        );

        Project project =
                new Project();

        project.setOrganisation(
                currentOrganisation
        );

        when(
                investigationRepository
                        .findByIdAndOrganisationId(
                                18L,
                                1L
                        )
        ).thenReturn(
                Optional.of(investigation)
        );

        when(
                projectRepository
                        .findByIdAndOrganisationId(
                                20L,
                                1L
                        )
        ).thenReturn(
                Optional.of(project)
        );

        when(
                investigationRepository.save(
                        investigation
                )
        ).thenReturn(
                investigation
        );

        SiteInvestigation result =
                service.assignProject(
                        18L,
                        20L
                );

        assertSame(
                project,
                result.getProject()
        );

        verify(
                investigationRepository
        ).save(investigation);
    }

    @Test
    void shouldBlockCrossOrganisationProjectAssignment() {

        SiteInvestigation investigation =
                new SiteInvestigation(
                        "INV-TENANT-005",
                        "Borehole",
                        "Harlow",
                        "PLANNED",
                        "2026-09-10",
                        "Cross tenant assignment test"
                );

        investigation.setOrganisation(
                currentOrganisation
        );

        when(
                investigationRepository
                        .findByIdAndOrganisationId(
                                18L,
                                1L
                        )
        ).thenReturn(
                Optional.of(investigation)
        );

        when(
                projectRepository
                        .findByIdAndOrganisationId(
                                2L,
                                1L
                        )
        ).thenReturn(
                Optional.empty()
        );

        RuntimeException exception =
                assertThrows(
                        RuntimeException.class,
                        () ->
                                service.assignProject(
                                        18L,
                                        2L
                                )
                );

        assertEquals(
                "Project not found",
                exception.getMessage()
        );

        assertNull(
                investigation.getProject()
        );

        verify(
                investigationRepository,
                never()
        ).save(
                any(SiteInvestigation.class)
        );

        verify(
                projectRepository,
                never()
        ).findById(2L);
    }
}