-- =========================================================
-- GeoTrack
-- V1 - Initial GeoTrack Schema
-- =========================================================
--
-- This migration provides the initial PostgreSQL schema
-- required by GeoTrack.
--
-- The CREATE TABLE IF NOT EXISTS statements are deliberate.
--
-- GeoTrack's existing local development database was created
-- before Flyway was introduced and has been baselined at
-- version 0. Therefore:
--
--   - On the existing local database, these tables already
--     exist and will be left untouched.
--
--   - On a new production database, Flyway will create the
--     complete GeoTrack schema from scratch.
--
-- Hibernate is configured with ddl-auto=validate, so the
-- application validates this schema rather than modifying it.
-- =========================================================


-- =========================================================
-- ORGANISATIONS
-- =========================================================

CREATE TABLE IF NOT EXISTS organisations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    enabled BOOLEAN NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT ukkl9j7yfh8wyijpxig7f1nd6oa UNIQUE (name)
);


-- =========================================================
-- USERS
-- =========================================================

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    full_name VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    organisation_id BIGINT,

    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7
        UNIQUE (email),

    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6
        UNIQUE (username),

    CONSTRAINT fka1nclli5p7wblkociovr2hwbs
        FOREIGN KEY (organisation_id)
        REFERENCES organisations(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique
    ON users (LOWER(email))
    WHERE email IS NOT NULL;


-- =========================================================
-- PROJECTS
-- =========================================================

CREATE TABLE IF NOT EXISTS project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name VARCHAR(255),
    description VARCHAR(255),
    location VARCHAR(255),
    project_name VARCHAR(255),
    status VARCHAR(255),
    project_reference VARCHAR(255),
    start_date DATE,
    target_completion_date DATE,
    organisation_id BIGINT,

    CONSTRAINT fkbfcohpsa6y8oliipd41eldc79
        FOREIGN KEY (organisation_id)
        REFERENCES organisations(id)
);


-- =========================================================
-- SITE INVESTIGATIONS
-- =========================================================

CREATE TABLE IF NOT EXISTS site_investigation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date VARCHAR(30),
    investigation_reference VARCHAR(50),
    investigation_type VARCHAR(100),
    location VARCHAR(200),
    notes VARCHAR(1000),
    status VARCHAR(50),
    project_id BIGINT,
    organisation_id BIGINT,

    CONSTRAINT fk3a5jtfonmutdm965x2x7c9r2i
        FOREIGN KEY (organisation_id)
        REFERENCES organisations(id),

    CONSTRAINT fkrwxro5bm7vvj8e8olipr13djt
        FOREIGN KEY (project_id)
        REFERENCES project(id)
);


-- =========================================================
-- INVITATIONS
-- =========================================================

CREATE TABLE IF NOT EXISTS invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accepted BOOLEAN NOT NULL,
    accepted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    email VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    organisation_id BIGINT NOT NULL,

    CONSTRAINT uk6a03cl7cgxqwekvwbi3dmdruk
        UNIQUE (token_hash),

    CONSTRAINT fk5biqc9oqg3bna6s2bqqx0y0u1
        FOREIGN KEY (organisation_id)
        REFERENCES organisations(id)
);